experiment:
  name: "sam3_pro"
  output_dir: "outputs"

runtime:
  batch_size: 10
  workers: 5
  epochs: 8
  precision: "bf16"

data:
  train_image_root: ["/data/datasets/rs/LoveDA/img_dir/train","/data/datasets/rs/Potsdam/images/train",
                    "/data/datasets/rs/Vaihingen/images/train","/data1/datasets/zhengbo/roaddataset/deepglobe/images/train",
                    "/data1/datasets/zhengbo/roaddataset/chn6/images/train","/data1/datasets/zhengbo/roaddataset/mass/images/train"]
  image_size: 560

model:
  name: "/home/cz/codes/githubs/sam3/checkpoints/sam3.pt"
  wrapper: "sam3"
  lora: "linear_r-8"

method:
  disable_attention_hijack_filter: true
  enable_window_phase_artifact_loss: True

optimizer:
  name: "adamw"
  lr: 1.0e-5
  lr_last: 0.0
  wd: 0.1
  warmup: 0
  scheduler: "const"

logging:
  wandb: false
  wandb_mode: "offline"
